export const ServicesToPathMapping: any[] = [
  { cat_id: 20, path: 'landline-postpaid', searchValue: 'Landline Postpaid', },
  { cat_id: 18, path: 'water', searchValue: 'Water', },
  // { cat_id: 1, path: 'insurance', searchValue: 'Insurance', },
  { cat_id: 5, path: 'hospital', searchValue: 'Hospital', },
  { cat_id: 16, path: 'electricity', searchValue: 'Electricity', },
  { cat_id: 6, path: 'health-insurance', searchValue: 'Health Insurance', },
  { cat_id: 3, path: '../bbps/service/mobile-postpaid', searchValue: 'Mobile Postpaid', },
  { cat_id: 23, path: 'fasttag', searchValue: 'Fastag', },
  { cat_id: 17, path: 'gas', searchValue: 'Gas', },
  // { cat_id: 1, path: 'subscription', searchValue: 'Subscription', },
  { cat_id: 25, path: 'housing-society', searchValue: 'Housing Society', },
  { cat_id: 24, path: 'cable-tv', searchValue: 'Cable TV', },
  { cat_id: 19, path: 'broadband-postpaid', searchValue: 'Broadband Postpaid', },
  { cat_id: 22, path: 'lpg-gas', searchValue: 'LPG Gas', },
  // { cat_id: 1, path: 'municipal-services', searchValue: 'Municipal Services', },
  { cat_id: 4, path: 'loan-repayment', searchValue: 'Loan Repayment', },
  { cat_id: 7, path: 'life-insurance', searchValue: 'Life Insurance', },
  // { cat_id: 1, path: 'credit-card', searchValue: 'Credit Card', },
  { cat_id: 27, path: 'municipal-taxes', searchValue: 'Municipal Taxes', },
  { cat_id: 2, path: '../bbps/service/dth', searchValue: 'DTH', },
  { cat_id: 26, path: 'education-fees', searchValue: 'Education Fees', },
]

export const IamgeMapping: any[] = [

  { name: 'Mobile prepaid.svg', imageUri: require('../../assets/compresspng/Mobile-prepaid.png'), },
  { name: 'DTH.svg', imageUri: require('../../assets/compresspng/DTH.png'), },
  { name: 'Mobile postpaid.svg', imageUri: require('../../assets/compresspng/Mobile-postpaid.png'), },
  { name: 'Loan Repay.svg', imageUri: require('../../assets/compresspng/Loan-Repay.png'), },
  { name: 'Hospital.svg', imageUri: require('../../assets/compresspng/Hospital.png'), },
  { name: 'Health Insurance.svg', imageUri: require('../../assets/compresspng/Health-Insurance.png'), },
  { name: 'Life Insurance.svg', imageUri: require('../../assets/compresspng/Life-Insurance.png'), },
  { name: 'AEPS.svg', imageUri: require('../../assets/compresspng/AEPS.png'), },
  { name: 'DMT.svg', imageUri: require('../../assets/compresspng/DMT.png'), },
  { name: 'New Aadhar.svg', imageUri: require('../../assets/compresspng/New-Aadhar.png'), },
  { name: 'Print PVC.svg', imageUri: require('../../assets/compresspng/Print-PVC.png'), },
  { name: 'Computer_education.svg', imageUri: require('../../assets/compresspng/Computer_education.png'), },
  { name: 'Electricity.svg', imageUri: require('../../assets/compresspng/Electricity.png'), },
  { name: 'Gas.svg', imageUri: require('../../assets/compresspng/Gas.png'), },
  { name: 'Water.svg', imageUri: require('../../assets/compresspng/Water.png'), },
  { name: 'Broadband.svg', imageUri: require('../../assets/compresspng/Broadband.png'), },
  { name: 'Landline.svg', imageUri: require('../../assets/compresspng/Landline.png'), },
  { name: 'LPG gas.svg', imageUri: require('../../assets/compresspng/LPG-gas.png'), },
  { name: 'Fastag.svg', imageUri: require('../../assets/compresspng/Fastag.png'), },
  { name: 'Cable_tv.svg', imageUri: require('../../assets/compresspng/Cable_tv.png'), },
  { name: 'Housing society.svg', imageUri: require('../../assets/compresspng/Housing-society.png'), },
  { name: 'Education Fee.svg', imageUri: require('../../assets/compresspng/Education-Fee.png'), },
  { name: 'Municipality fees.svg', imageUri: require('../../assets/compresspng/Municipality-fees.png'), },
  { name: 'Pancard.svg', imageUri: require('../../assets/compresspng/Pancard.png'), },
  { name: 'pmfby.svg', imageUri: require('../../assets/compresspng/pmfby.png'), },
]
